scheduler:
  municipality-ids: 2281, 2282, 2283

email:
  extension-error:
    recipient: junit-recipient@test.se
    sender: junit-sender@test.se
  lantmateriet:
    recipient: junit-recipient@test.se
    sender: junit-sender@test.se
  status:
    recipient: junit-recipient@test.se
    sender: junit-sender@test.se
integration:
  archive:
    # Sets the maximum file size for the archive integration, in bytes. E.g. 100 * 1024 * 1024 = 104857600 (100 MB)
    maximum-file-size: 100000
    oauth2:
      clientId: client-id
      clientSecret: client-secret
      tokenUrl: ${sundsvall.token-uri}
    url: http://archive.url
  arendeexport:
    connectTimeout: 1
    readTimeout: 2
    url: http://arendeexport.url
  fb:
    database: database
    password: password
    url: http://fbservice.url
    username: username
  messaging:
    oauth2:
      clientId: client-id
      clientSecret: client-secret
      tokenUrl: ${sundsvall.token-uri}
    url: http://messaging.url
long-term-archive:
  url: http://sundsvall-junit-test.se
spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6.14:///junittest
  jpa:
    properties:
      jakarta:
        persistence:
          schema-generation:
            database:
              action: update
            scripts:
              action: create
              create-target: target/database/generated-schema.sql
            create-source: metadata
      hibernate:
        hbm2ddl:
          schema-generation:
            script:
              append: false
        format_sql: true
sundsvall:
  token-uri: http://token.uri
