/*
 * Messaging API
 * API used to send messages, as e-mail or SMS
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package se.sundsvall.sundsvall.messaging.vo;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * ServiceErrorResponse
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-12-17T10:28:24.465012+01:00[Europe/Berlin]")
public class ServiceErrorResponse {
  @JsonProperty("httpCode")
  private Integer httpCode = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("technicalDetails")
  private TechnicalDetails technicalDetails = null;

  public ServiceErrorResponse httpCode(Integer httpCode) {
    this.httpCode = httpCode;
    return this;
  }

   /**
   * Get httpCode
   * @return httpCode
  **/
  @Schema(description = "")
  public Integer getHttpCode() {
    return httpCode;
  }

  public void setHttpCode(Integer httpCode) {
    this.httpCode = httpCode;
  }

  public ServiceErrorResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @Schema(description = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public ServiceErrorResponse technicalDetails(TechnicalDetails technicalDetails) {
    this.technicalDetails = technicalDetails;
    return this;
  }

   /**
   * Get technicalDetails
   * @return technicalDetails
  **/
  @Schema(description = "")
  public TechnicalDetails getTechnicalDetails() {
    return technicalDetails;
  }

  public void setTechnicalDetails(TechnicalDetails technicalDetails) {
    this.technicalDetails = technicalDetails;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceErrorResponse serviceErrorResponse = (ServiceErrorResponse) o;
    return Objects.equals(this.httpCode, serviceErrorResponse.httpCode) &&
        Objects.equals(this.message, serviceErrorResponse.message) &&
        Objects.equals(this.technicalDetails, serviceErrorResponse.technicalDetails);
  }

  @Override
  public int hashCode() {
    return Objects.hash(httpCode, message, technicalDetails);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceErrorResponse {\n");
    
    sb.append("    httpCode: ").append(toIndentedString(httpCode)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    technicalDetails: ").append(toIndentedString(technicalDetails)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
